name: products_manager_mvvm
description: A reproduction of already existing app into mvvm architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_storage: ^11.1.2
  flutter_slidable: ^3.0.0
  cloud_firestore: ^4.13.2
  flutter_riverpod:
  provider: ^6.1.1
  logger:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
